'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { DocumentTextIcon, SparklesIcon, StarIcon } from '@heroicons/react/24/outline';
import { StarIcon as StarSolidIcon } from '@heroicons/react/24/solid';

type SummaryType = 'BRIEF' | 'DETAILED' | 'ELI5' | 'TECHNICAL' | 'LITERATURE_REVIEW';

interface SummaryPanelProps {
  paperId: string;
  paperTitle: string;
  onClose?: () => void;
}

interface Summary {
  summary: string;
  type: SummaryType;
  modelUsed: string;
  tokensUsed: number;
  cached: boolean;
  generatedAt: Date;
}

interface SummaryState {
  [key: string]: Summary | undefined;
}

const SUMMARY_TYPES: { type: SummaryType; label: string; icon: string; description: string }[] = [
  { type: 'BRIEF', label: 'Brief', icon: '⚡', description: '3 bullet points' },
  { type: 'DETAILED', label: 'Detailed', icon: '📋', description: 'Full breakdown' },
  { type: 'ELI5', label: 'ELI5', icon: '🎓', description: 'Simple explanation' },
  { type: 'TECHNICAL', label: 'Technical', icon: '⚙️', description: 'Deep dive' },
  {
    type: 'LITERATURE_REVIEW',
    label: 'Lit Review',
    icon: '📚',
    description: 'For your report',
  },
];

export default function SummaryPanel({ paperId, paperTitle, onClose }: SummaryPanelProps) {
  const [activeTab, setActiveTab] = useState<SummaryType>('BRIEF');
  const [summaries, setSummaries] = useState<SummaryState>({});
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [rating, setRating] = useState(0);

  // Fetch summary when tab changes
  useEffect(() => {
    if (summaries[activeTab]) {
      return; // Already loaded
    }

    const fetchSummary = async () => {
      setIsLoading(true);
      setError(null);

      try {
        const response = await fetch('/api/ai/summarize', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${localStorage.getItem('accessToken')}`,
          },
          body: JSON.stringify({
            paperId,
            summaryType: activeTab,
          }),
        });

        if (!response.ok) {
          const data = await response.json();
          throw new Error(data.error?.message || 'Failed to generate summary');
        }

        const data = await response.json();
        setSummaries((prev) => ({
          ...prev,
          [activeTab]: data.data,
        }));
      } catch (err: any) {
        setError(err.message);
      } finally {
        setIsLoading(false);
      }
    };

    fetchSummary();
  }, [activeTab, paperId, summaries]);

  const currentSummary = summaries[activeTab];

  const handleExport = async (format: 'txt' | 'docx') => {
    if (!currentSummary) return;

    const content = `${paperTitle}\n\n${currentSummary.summary}\n\n---\nGenerated by NeuroAI\nModel: ${currentSummary.modelUsed}`;

    if (format === 'txt') {
      const element = document.createElement('a');
      element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
      element.setAttribute('download', `${paperTitle.substring(0, 50)}.txt`);
      element.style.display = 'none';
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    }

    // DOCX export would require docx library
    // For now, just export as text
  };

  return (
    <div className="flex flex-col h-full bg-gradient-to-b from-surface to-void rounded-xl overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between p-6 border-b border-glass">
        <div className="flex items-center gap-3">
          <SparklesIcon className="w-5 h-5 text-indigo" />
          <h3 className="text-lg font-semibold text-star">AI Summary</h3>
          {currentSummary?.cached && (
            <span className="text-xs bg-elevated px-2 py-1 rounded text-secondary">cached</span>
          )}
        </div>
        {onClose && (
          <button
            onClick={onClose}
            className="text-secondary hover:text-primary transition-colors"
          >
            ✕
          </button>
        )}
      </div>

      {/* Tab Selector */}
      <div className="flex gap-2 px-6 pt-4 overflow-x-auto border-b border-glass">
        {SUMMARY_TYPES.map(({ type, label, icon }) => (
          <button
            key={type}
            onClick={() => setActiveTab(type)}
            className={`px-4 py-2 rounded-lg whitespace-nowrap font-mono text-sm 
                        transition-all duration-200 flex items-center gap-2
                        ${
                          activeTab === type
                            ? 'bg-indigo text-void font-semibold'
                            : 'bg-glass hover:bg-glass-hover text-secondary'
                        }`}
          >
            <span>{icon}</span>
            <span>{label}</span>
          </button>
        ))}
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto p-6">
        <AnimatePresence mode="wait">
          {isLoading ? (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center justify-center h-full"
            >
              <div className="text-center">
                <div className="inline-block animate-spin mb-3">
                  <SparklesIcon className="w-6 h-6 text-indigo" />
                </div>
                <p className="text-secondary">Generating {SUMMARY_TYPES.find((t) => t.type === activeTab)?.label.toLowerCase()} summary...</p>
              </div>
            </motion.div>
          ) : error ? (
            <motion.div
              key="error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center justify-center h-full"
            >
              <div className="text-center">
                <p className="text-rose mb-3">❌ {error}</p>
                <button
                  onClick={() => setActiveTab(activeTab)}
                  className="px-4 py-2 bg-indigo text-void rounded-lg font-monk text-sm hover:shadow-glow-indigo-md transition-all"
                >
                  Retry
                </button>
              </div>
            </motion.div>
          ) : currentSummary ? (
            <motion.div
              key={activeTab}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="space-y-4"
            >
              {/* Summary Content with streaming effect */}
              <div className="bg-elevated border border-glass rounded-lg p-5 font-mono text-sm leading-relaxed text-primary">
                {currentSummary.summary.split('\n\n').map((paragraph, i) => (
                  <p key={i} className="mb-3 last:mb-0">
                    {paragraph}
                  </p>
                ))}
              </div>

              {/* Rating */}
              <div className="flex items-center gap-3 px-4 py-3 bg-glass rounded-lg">
                <span className="text-sm text-secondary">How helpful?</span>
                <div className="flex gap-1">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <button
                      key={star}
                      onClick={() => setRating(star)}
                      className="transition-all hover:scale-110"
                    >
                      {star <= rating ? (
                        <StarSolidIcon className="w-5 h-5 text-amber" />
                      ) : (
                        <StarIcon className="w-5 h-5 text-secondary hover:text-amber" />
                      )}
                    </button>
                  ))}
                </div>
              </div>

              {/* Meta Info */}
              <div className="text-xs text-secondary space-y-1">
                <p>🤖 Model: {currentSummary.modelUsed}</p>
                <p>📊 Tokens: {currentSummary.tokensUsed}</p>
              </div>
            </motion.div>
          ) : null}
        </AnimatePresence>
      </div>

      {/* Footer Actions */}
      {currentSummary && (
        <div className="flex gap-2 p-6 border-t border-glass">
          <button
            onClick={() => {
              navigator.clipboard.writeText(currentSummary.summary);
              alert('Copied to clipboard!');
            }}
            className="flex-1 px-4 py-2 bg-glass hover:bg-glass-hover border border-glass 
                       rounded-lg text-sm font-mono text-secondary transition-all"
          >
            Copy
          </button>
          <button
            onClick={() => handleExport('txt')}
            className="flex-1 px-4 py-2 bg-indigo hover:shadow-glow-indigo-md text-void 
                       rounded-lg text-sm font-mono transition-all"
          >
            Export
          </button>
        </div>
      )}
    </div>
  );
}
